### ISSUE TITLE
Date format support would be great

### ISSUE THREAD

**Issue by loeffel-io** [mehanizm/airtable#11]
A method would be great to convert a time.Time to the airtable date format

**Comment by mehanizm** [comment]
Hi Lucas,
thank for using lib and the feedback!

Airtable date format is a string with ISO8601 formatted date 

For example, to parse this string to golang time.Time use 
`fieldDT, err := time.Parse("2006-01-02T15:04:05.999Z", fieldName)`

If you want to convert your time.Time variable to airtable string use
`airtableDT := varInTime.Format("2006-01-02T15:04:05.999Z")`

Or you can use Typecast parameter in `Record` struct (toggle it to true) to allow Airtable try to perform best-effort for data conversion.

But for your comfort I've added conversion functions to the lib
`ToDateTime(field interface{})` – to convert to from airtable field to time.Time
`FromDateTime` vice versa

0.2.7+

**Comment by loeffel-io** [comment]
❤️
