### ISSUE TITLE
GetRecords().Do returns nil

### ISSUE THREAD

**Issue by phyzixmusic** [mehanizm/airtable#12]
Having issues getting any data back from GetRecords().Do()

Anyone else facing the same issue?

**Comment by mehanizm** [comment]
Hi, @phyzixmusic 
Thanks for the issue.

Please, provide more info about your problem. For example all the code that doesn't work.

**Comment by phyzixmusic** [comment]
Hi
Thanks for getting back to me so quick

I am using the exact code you supplied in list records example

records, err := table.GetRecords().Do()

this line returns nil

**Comment by mehanizm** [comment]
Please, provide result of the print:

`fmt.Printf("%v\n%+v\n%+v\n%+v\n", err, records, table, client)`
