### ISSUE TITLE
client.GetBases function does not exist

### ISSUE THREAD

**Issue by whoiscarlo** [mehanizm/airtable#14]
Hey first off wanted to say thank you for creating and maintaining this package!

I just started using it and found that the function `client.GetBases` that is found on the read me returns an error of `client.GetBases undefined (type *airtable.Client has no field or method GetBases)compiler[MissingFieldOrMethod]`

I searched the client.go file and found no traces of the **GetBases** method. Is there something that I'm missing or was this method never implemented?

**Comment by mehanizm** [comment]
@whoiscarlo thx for your patient.
I've pushed new tag of the library so you can get it with `go get`
Please, let me know if there are any other issues.

**Comment by whoiscarlo** [comment]
Much appreciated! Thank you 🥳
