### ISSUE TITLE
Pass custom context.Context?

### ISSUE THREAD

**Issue by akfaew** [mehanizm/airtable#15]
I don't think it's currently possible to pass a custom context. Would it be possible to add this functionality?

**Comment by mehanizm** [comment]
@akfaew , thx for the idea.
Please, tell us more about your scenario?

**Comment by akfaew** [comment]
I'd like to use the library in a Google AppEngine environment. It's not a typical hosting environment, it is able to spin up new instances based on how many requests it receives. It can also destroy instances if they are unused. For it to work, every connection needs a special AppEngine-specific ctx.

This thread explains what happens when a non-AppEngine context is used: https://stackoverflow.com/questions/43765014/appengine-using-a-context-not-associated-with-a-request

Here is someone asking why a context.Background() won't work: https://groups.google.com/g/google-appengine-go/c/1xI3_JJyYp8

**Comment by mehanizm** [comment]
Sorry, but I don't think that such GAE specific functionality should be supported in general purpose library.

As a solution you can fork this repo and update methods in client.go to use custom context.

**Comment by akfaew** [comment]
This is not GAE specific functionality. All libraries that I've used so far support custom contexts. It's standard practice, there are many other uses, such as managing timeouts.

**Comment by akfaew** [comment]
Sure. Here is a very small library that just fetches Hacker News comments: https://github.com/peterhellberg/hn/blob/master/client.go
You can pass your own http client to it (that's equivalent to what we're talking about).

**Comment by akfaew** [comment]
Here is a commit that fixes the issue for the Slack library: https://github.com/slack-go/slack/commit/0389f449ad7250e769ad2b0dd67cb31af57133a2

**Comment by mehanizm** [comment]
Thanks a lot
I don't understand how passing http client fixing the context issue in hacker news example.

But example from Slack is good. So we need to add pair *Context method for all existing functionality.
It's not difficult, but I need to find time for it.

**Comment by akfaew** [comment]
If you want to pass a custom context to all network calls, just create a new http client with that custom context. It's a more powerful way of achieving the same thing, and I think it was easier for the library author.

**Comment by mehanizm** [comment]
But context is request scope or I didn't catch your idea.

Nevertheless I've added support of the custom context and custom http client to the lib. Please, use. 
0.3+

**Comment by akfaew** [comment]
Thanks.

I think versioning is broken for the project, as some tags have the 'v' prefix and some don't. Go things that v0.2.7 is the latest version.

**Comment by mehanizm** [comment]
Fixed.
Thx
