### ISSUE TITLE
UpdateRecordPartial does not update a partial record. Will update the whole record.

### ISSUE THREAD

**Issue by tamsanh** [mehanizm/airtable#4]
When I try to use `UpdateRecordPartial` by passing a `map[string]interface{}` with a subset of fields filled in, the Airtable data will have everything erased Except for the fields filled in.

Btw, thanks for that Offset fix that was pushed 4 days ago; it was impeccably timed.

**Comment by tamsanh** [comment]
I double checked the API, and was totally wrong. Your code works, it was my code that was erroneously adding `nil`s for keys that it shouldn't have. My bad, thanks again for the great library.

**Comment by mehanizm** [comment]
Happy to hear that my lib is helpful! If you ever do have a problem feel free to open an issue.
