### ISSUE TITLE
Add records example not working

### ISSUE THREAD

**Issue by freekdegreef** [mehanizm/airtable#6]
Not a bug exactly but I can't seem to get the 'Add records' example to work. Got as far to find out that the `map[string]interface` is missing `{}` after it in order for the code to compile properly but that is as far I've gotten with my basic Go knowledge. 'Get record by ID' works fine so it's not my credentials/base. Anyone seeing what is missing here or am I overlooking something crucial?

**Comment by mehanizm** [comment]
You're absolutely right! It's the misprint in the readme, I'll fix it.

100% working examples you can always find in the tests.

Thank you for the feedback!

**Comment by mehanizm** [comment]
Fixed 0.2.3+
